ad

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -40,8 +40,7 @@ jobs:
       packages: write
       pull-requests: write
     outputs:
-      projects: ${{ steps.semver.outputs.old_version }}
-      date_tag: ${{ steps.semver.outputs.new_version }}
+      new_version: ${{ steps.semver.outputs.new_version }}
 
     steps:
     - name: Checkout
@@ -74,15 +73,13 @@ jobs:
           minor)  major=$(get_version majorVersion); minor=$(get_version nextMinorVersion); patch=0 ;;
           *)      major=$(get_version majorVersion); minor=$(get_version minorVersion); patch=$(get_version nextIncrementalVersion);;
         esac
-        echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
         NEW_VERSION="$major.$minor.$patch"
-        # If the event is a pull request, append -SNAPSHOT
+        # Ensure release are performed from 'master' only. For other branches, append -SNAPSHOT
         if [[ "${{ github.ref_name }}" != "master" ]]; then
           NEW_VERSION="${NEW_VERSION}-SNAPSHOT"
         fi
         echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
-        echo "::notice title=Old Version::$OLD_VERSION"
-        echo "::notice title=New Version::$NEW_VERSION"
+        echo "::notice title=Version Update::$OLD_VERSION -> $NEW_VERSION"
 
     - name: Update Project Version
       working-directory: ${{ env.PROJECT_DIR }}
@@ -134,36 +131,51 @@ jobs:
           --base ${{ github.ref_name }})
         echo "pr_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
         echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
-        echo "::notice title=PR URL::$pr_url"
+        echo "::notice title=PR::$pr_url"
 
-    - name: Wait on PR checks
+    - name: Merge PR
       if: github.event_name != 'pull_request'
       run: |
-        echo "Waiting for GitHub sync..."
-        sleep 15
         PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pr_url }}" | grep -oE '[0-9]+$')
-        echo "PR_NUMBER=$PR_NUMBER"
-        gh pr view "$PR_NUMBER" --json state
-        gh pr checks "$PR_NUMBER"
-        echo "Waiting for Pull-Request: ${{ steps.create_pr.outputs.pr_url }} status check(s)..."
-        output=$(timeout 45m gh pr checks --watch "$PR_NUMBER" 2>&1)
-        return_code=$?
-        echo "$output" | tail -n 10
-        if [[ $return_code -ne 0 ]]; then
-          error "Failed on waiting for status checks" $return_code
+        PR_MERGE_STATE=$(gh pr view "$PR_NUMBER" --json 'mergeStateStatus' --jq '.mergeStateStatus' )
+        PR_MERGEABLE=$(gh pr view "$PR_NUMBER" --json 'mergeable' --jq '.mergeable' )
+        if [[ "$PR_MERGE_STATE" == "CLEAN" && "$PR_MERGEABLE" == "MERGEABLE" ]]; then
+          echo "✅ PR is mergeable without conflicts."
+          if gh pr merge "$PR_NUMBER" --repo "${{ github.repository }}" --admin --merge --delete-branch; then
+            echo "✅ PR #$PR_NUMBER merged successfully!"
+            exit 0
+          fi
         fi
+        echo "❌ PR has merge conflicts or an unknown merge status: $PR_MERGE_STATE"
+        exit 1
 
-    - name: Automerge PR
-      if: github.event_name != 'pull_request'
-      run: |
-        if ! gh pr merge "${{ steps.create_pr.outputs.pr_url }}" --repo "${{ github.repository }}"" --admin --merge --delete-branch; then
-          error "Merge failed! Please check for conflicts."
-        fi
-
-    - name: action-slack
+    - name: clean debug
       if: failure() && steps.create_pr.outcome != 'success'
       run: |
         echo "Run action-slack"
         echo "Result of 'Commit & Push' step was '${{ steps.create_pr.outcome }}'"
         echo "pr url: ${{ steps.create_pr.outputs.pr_url }}"
-        echo "pr branch: #BRANCH_NAME"
+        echo "pr branch: ${{ steps.create_pr.outputs.pr_branch }}"
+
+    - name: Cleanup
+      if: always()
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        PR_URL: ${{ steps.create_pr.outputs.pr_url }}
+        BRANCH_NAME: ${{ steps.create_pr.outputs.pr_branch }}
+      run: |
+        echo "Cleaning up GitHub PR and branch..."
+        # Check if PR exist and delete it
+        if [[ -n "$PR_URL" ]]; then
+          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
+          gh pr close "$PR_NUMBER" --delete-branch || echo "Failed to close PR."
+          echo "✅ Deleted PR #$PR_NUMBER."
+        fi
+        # Check if branch exists and delete it
+        if [[ -n "$BRANCH_NAME" ]]; then
+          if gh api repos/${{ github.repository }}/branches/$BRANCH_NAME >/dev/null 2>&1; then
+            gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME || echo "Failed to delete branch."
+            echo "✅ Deleted branch $BRANCH_NAME."
+          fi
+        fi
+        echo "Finished cleaning."
